
on:
    release:
      types: [created]  
jobs:
    release:
      name: release ${{ matrix.target }} (with non-required env)
      runs-on: ubuntu-latest
      if: github.event_name == 'release'
      strategy:
        fail-fast: false
        matrix:
          include:
            - target: x86_64-pc-windows-gnu
              archive: zip
            - target: x86_64-unknown-linux-musl
              archive: tar.gz
            - target: x86_64-apple-darwin
              archive: zip
            - target: wasm32-wasi
              archive: zip tar.gz
      steps:
        - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        - name: Compile and release
          uses: rust-build/rust-build.action@59be2eda2b24dd30430ba05988d8c6ccef4c8da0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            RUSTTARGET: ${{ matrix.target }}
            ARCHIVE_TYPES: ${{ matrix.archive }}
            MINIFY: "yes"
   